name: Gatsby Publish

on:
  push:
    branches:
      - mater

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: 9f07b38fc40fabc41c99c2a39fbd5134414bef65
          deploy-branch: gh-pages
